# Generated by Django 2.0.2 on 2018-03-08 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampstart', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 20, 45, 49, 812582))),
                ('timestampend', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=9)),
                ('destination', models.CharField(max_length=9)),
            ],
        ),
    ]
